[package]
name = "metlink_gtfs_cron"
version = "0.1.0"
edition = "2018"

[dependencies]
metlink_gtfs_lib = { path = "../metlink_gtfs_lib" }
tokio = { version = "1.8", features = ["full"] }
eyre = "0.6"
color-eyre = "0.5"
log = "0.4.14"
env_logger = "0.9.0"
